project:
  name: "CHANGE_ME"
  primary_languages:
    - "python"

workflow:
  sessions_dir: ".session"
  always_on_compliance: true
  max_parallel_agents: 5
  autofix_allowed: true
  max_remediation_loops: 2
  # default|tdd — influences action-planner output (task ordering/dependencies).
  strategy: "default"
  # When true, code tasks must specify acceptance_criteria.verifications[] (so gates can run evidence deterministically).
  require_verifications_for_code_tasks: true
  # When true, the workflow generates USER_STORIES and requires tasks to reference them.
  require_user_stories: true
  # E2E mode: off|optional|required. E2E is configured via `.claude/at/e2e.json`.
  e2e_mode: "optional"

docs:
  registry_path: "docs/DOCUMENTATION_REGISTRY.json"
  min_review_tier: 2
  # Corporate-grade default: enforce registry usage and prevent drift.
  require_registry: true
  sections_enabled: false

learning:
  enabled: true
  dir: ".claude/agent-team/learning"
  max_sessions: 50
  emit_adr_stubs: true
  emit_sessionstart_context: true
  sessionstart_context_max_chars: 1200

lsp:
  enabled: true
  # fail|warn|skip — applies when actions.json includes lsp verifications.
  mode: "skip"

audit:
  enabled: false
  traces_enabled: false

telemetry:
  enabled: true

# Commands are intentionally project-editable.
# Prefer stable, CI-friendly commands and keep them fast.
commands:
  # When true, `scripts/quality/run_quality_suite.py` may use `.claude/at/languages/*.json` suggested suites
  # as defaults for missing language commands. Keep false by default to avoid surprise toolchain assumptions.
  allow_language_pack_defaults: false
  python:
    format: "python -m ruff format ."
    lint: "python -m ruff check ."
    typecheck: "python -m mypy ."
    test: "python -m pytest -q"
    build: ""

policies:
  forbid_secrets_globs:
    - ".env"
    - ".env.*"
    - "secrets/**"
